org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.4
forge_version_range=[47.4.4,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=nsukpreviewtoggle
mod_name=NSUK 预览切换补丁
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.mskb.nsukpreviewtoggle
mod_authors=MSKB
mod_description=为 New Sim-U-Kraft 大建筑预览添加范围框/详细方块预览切换。
