org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.4
forge_version_range=[47.4.4,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=sbpinventoryswitch
mod_name=精妙背包切换补丁
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.mskb.sbpinventoryswitch
mod_authors=MSKB
mod_description=为 Sophisticated Backpacks 添加玩家背包与精妙背包界面的快捷切换。
