org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.4
forge_version_range=[47.4.4,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=nsukmanifestplus
mod_name=NSUK 更好的清单补丁
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.mskb.nsukmanifestplus
mod_authors=MSKB
mod_description=增强 New Sim-U-Kraft 清单界面，显示材料库存、缺少过滤和刷新进度。
