org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=nsukbeautifulfarm
mod_name=NSUK Beautiful Farm Patch
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.mskb.nsukbeautifulfarm
mod_authors=MSKB
mod_description=Adds configurable visual farm decorations to New Sim-U-Kraft farmland box selection and construction.
